//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int IdAdministrator { get; set; }
        public string FullName { get; set; }
        public int Users_IdUser { get; set; }
        public int User_IdUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
