//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Status = 0;
        }
    
        public int IdAppointment { get; set; }
        public System.DateTime AttendedDate { get; set; }
        public long Duration { get; set; }
        public short Status { get; set; }
        public string NotAttendedReason { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Procedure Procedure { get; set; }
    }
}
