//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetAppointmentInfo
    {
        public System.DateTime AttendedDate { get; set; }
        public long Duration { get; set; }
        public short Status { get; set; }
        public string FullName { get; set; }
        public string IdStudent { get; set; }
        public string Name { get; set; }
        public string CareerName { get; set; }
        public string Expr1 { get; set; }
    }
}
