//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStudent
    {
        public string IdStudent { get; set; }
        public string FullName { get; set; }
        public int IdCareer { get; set; }
        public string CareerName { get; set; }
        public int IdTutor { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public int IdUser { get; set; }
    }
}
